import { CourseItem } from "@/types";

export const COURSES: readonly CourseItem[] = [
  {
    id: "1",
    title: "Learn Figma from Basic",
    category: "UI/UX Design",
    thumb: "/images/courses/figma.jpg",
    instructor: "purepearl studio",
    price: "$25",
    period: "lifetime",
    rating: 4.5,
    level: "Beginner",
    lessonsCount: "17 Lessons",
    duration: "2 hours 16 mins",
    commentsCount: "59 Comments",
    studentsCount: "26+",
  },
  {
    id: "2",
    title: "Build Digital Asset",
    category: "Digital Illustration",
    thumb: "/images/courses/illustration.jpg",
    instructor: "purepearl studio",
    price: "$25",
    period: "lifetime",
    rating: 4.5,
    level: "Beginner",
    lessonsCount: "14 Lessons",
    duration: "1 hour 45 mins",
    commentsCount: "42 Comments",
    studentsCount: "26+",
  },
  {
    id: "3",
    title: "the Power of Big Data",
    category: "Data Science",
    thumb: "/images/courses/dashboard.jpg",
    instructor: "purepearl studio",
    price: "$25",
    period: "lifetime",
    rating: 4.5,
    level: "Beginner",
    lessonsCount: "21 Lessons",
    duration: "3 hours 10 mins",
    commentsCount: "86 Comments",
    studentsCount: "26+",
  },
  {
    id: "4",
    title: "Balancing Productivity and Self-Care",
    category: "Productivity",
    thumb: "/images/courses/developer.jpg",
    instructor: "purepearl studio",
    price: "$25",
    period: "lifetime",
    rating: 4.5,
    level: "Beginner",
    lessonsCount: "12 Lessons",
    duration: "1 hour 30 mins",
    commentsCount: "35 Comments",
    studentsCount: "26+",
  },
  {
    id: "5",
    title: "Mastering Money Management",
    category: "Freelance & Entrepreneurship",
    thumb: "/images/courses/growth.jpg",
    instructor: "purepearl studio",
    price: "$25",
    period: "lifetime",
    rating: 4.5,
    level: "Beginner",
    lessonsCount: "16 Lessons",
    duration: "2 hours 05 mins",
    commentsCount: "48 Comments",
    studentsCount: "26+",
  },
  {
    id: "6",
    title: "From Idea to Startup Success",
    category: "Freelance & Entrepreneurship",
    thumb: "/images/courses/collab.jpg",
    instructor: "purepearl studio",
    price: "$25",
    period: "lifetime",
    rating: 4.5,
    level: "Beginner",
    lessonsCount: "19 Lessons",
    duration: "2 hours 40 mins",
    commentsCount: "64 Comments",
    studentsCount: "26+",
  },
] as const;

export const CATEGORY_ROWS: readonly (readonly string[])[] = [
  [
    "Featured",
    "Music",
    "Drawing & Painting",
    "Marketing",
    "Animation",
    "Social Media",
    "UI/UX Design",
    "Creative Marketing",
  ],
  [
    "Digital Illustration",
    "Film & Video",
    "Crafts",
    "Freelance & Entrepreneurship",
    "Graphic Design",
    "Photography",
  ],
  ["Productivity", "Web Development", "Data Science", "Cooking"],
] as const;
